spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library?currentSchema=library_schema
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix:
      suffix:
  rabbitmq:
    host: rabbitmq
    port: 5672
server:
  port: 8081
credentials:
  secret: ${SECRET_KEY}